const products = [
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/x/w/o/-original-imagn9xqkzc2srnq.jpeg?q=70",
    brand: "Scorist",
    title: "Almond 1kg - Premium quality",
    rating: 3.5,
    price: 520,
    category: "Food products",
    brandLink: "/brand/scorist",
    productLink: "/products/details/:id",
    id: 1,
    description:
      "Scorist Almond 1kg - Premium Quality: Indulge in Scorist's premium quality almonds, perfect for snacking, baking, or cooking. These fresh, nutritious, and delicious almonds are a great source of protein and healthy fats.Ideal for maintaining a healthy lifestyle.",
    weight: "1kg",
    dimensions: "20cm x 15cm x 5cm",
    color: "Brown",
    material: "Plastic Bag",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/x/h/z/-original-imagpqjxchqrpmgc.jpeg?q=70",
    brand: "Adidas",
    title: "Men Printed Cotton Grey T-Shirt",
    rating: 4,
    price: 800,
    category: "Clothing",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 2,
    description:
      "Adidas Men Printed Cotton Grey T-Shirt: Experience ultimate comfort with this stylish Adidas T-shirt. Made from premium cotton, it features a trendy print and a perfect fit for casual wear. Ideal for everyday use, offering both style and breathability in a versatile grey color.",
    weight: "250g",
    dimensions: "30cm x 25cm x 2cm",
    color: "Grey",
    material: "Cotton",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/832/832/xif0q/vehicle-pull-along/t/z/i/monster-truck-cars-push-and-go-toy-trucks-friction-powered-cars-original-imahycx6nzdyygbn.jpeg?q=70&crop=false",
    brand: "Legoes",
    title: "4 pack Monster truck cars, push and go toy trucks",
    rating: 4,
    price: 350,
    category: "Toys",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 3,
    description:
      "Legoes 4 Pack Monster Truck Cars, Push and Go Toy Trucks: Ignite your child's imagination with these vibrant, durable monster trucks. This 4-pack of push and go toy trucks ensures endless fun and excitement. Perfect for indoor and outdoor play, promoting motor skills and creativity in children aged 3 and up.",
    weight: "800g",
    dimensions: "35cm x 25cm x 15cm",
    color: "Muticolor",
    material: "Plastic and rubber",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/312/312/xif0q/television/a/b/z/ua43t5450akxxl-samsung-original-imagtew8twpzcfrf.jpeg?q=70",
    brand: "Samsung",
    title: "SAMSUNG 108 cm (43 inch) Full HD LED Smart Tizen TV",
    rating: 4,
    price: 55000,
    category: "Electronics",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 4,
    description:
      "Samsung 108 cm (43 inch) Full HD LED Smart Tizen TV: Elevate your viewing experience with this Samsung Full HD Smart TV. Featuring a 108 cm (43 inch) LED display, it delivers stunning visuals and vibrant colors. Powered by Tizen, enjoy seamless streaming, apps, and smart home integration.",
    weight: "8 kg",
    dimensions: "108 cm (43 inch)",
    color: "Black",
    material: "Glass, Plastic and aluminium",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/snack-savourie/w/m/y/-original-imagg3c58r89pyxb.jpeg?q=70",
    brand: "Haldirams",
    title: "All in One Namkeen",
    rating: 4,
    price: 250,
    category: "Food products",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 5,
    description:
      "Haldiram's All in One Namkeen: Savor the delightful blend of flavors with Haldiram's All in One Namkeen. This mix includes a variety of crunchy snacks, offering a perfect balance of sweet, salty, and spicy.  Ideal for parties, gatherings, or a tasty snack anytime.",
    weight: "500g",
    dimensions: "20cm x 15cm x 5cm",
    color: "Brown",
    material: "Plastic Bag",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/jtsz3bk0/fruit/p/b/z/4-un-branded-whole-original-imafdrzgvrxwsgkr.jpeg?q=70",
    brand: "Natures Choice",
    title: "Pomegranate 2 Units",
    rating: 4.5,
    price: 99,
    category: "Fruits & Vegies",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 6,
    description:
      "Nature's Choice Pomegranate 2 Units: Enjoy the freshness and rich flavor of Nature's Choice Pomegranates. These juicy and nutrient-packed fruits are perfect for snacking, juicing, or adding to recipes. Ideal for a healthy and delicious addition to your daily diet.",
    weight: "600g",
    dimensions: "12cm x 12cm x 8cm",
    color: "Browny Red",
    material: "Edible product",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/jtsz3bk0/vegetable/b/8/4/2-potato-un-branded-no-whole-original-imafdsymh2aepaph.jpeg?q=70",
    brand: "Orignals",
    title: "Potato 1Kg",
    rating: 4.5,
    price: 40,
    category: "Fruits & Vegies",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 7,
    description:
      "Orignals Potato 1kg: Discover the quality and freshness of Orignals Potatoes. Perfect for cooking, baking, or frying, these versatile potatoes are a staple in every kitchen. Weight: 1kg. Dimensions: 20cm x 15cm x 10cm. Ideal for creating a variety of delicious dishes, from mashed potatoes to crispy fries.",
    weight: "1Kg",
    dimensions: "20cm x 15cm x 10cm",
    color: "Brown",
    material: "Edible product",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/l13whow0/fruit/k/t/k/1-1-unbranded-whole-original-imagcryhrfevxehw.jpeg?q=70",
    brand: "Fruiti",
    title: "Litchi 500 g",
    rating: 3.5,
    price: 216,
    category: "Fruits & Vegies",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 8,
    description:
      "Fruiti Litchi 500g: Savor the exotic sweetness of Fruiti Litchis. These juicy, fragrant fruits are perfect for snacking, desserts, or adding a tropical twist to your dishes. Enjoy a refreshing and healthy treat with every bite.",
    weight: "500g",
    dimensions: "15cm x 10cm x 8cm",
    color: "Brown",
    material: "Edible product",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/js4yljk0/vegetable/x/z/b/500-capsicum-green-un-branded-no-whole-original-imafdsyqecsbuvzh.jpeg?q=70",
    brand: "Naturals",
    title: "Capsicum Green 500 g",
    rating: 4.5,
    price: 42,
    category: "Fruits & Vegies",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 9,
    description:
      "Naturals Capsicum Green 500g: Enjoy the crisp, fresh taste of Naturals Green Capsicum. Perfect for salads, stir-fries, and a variety of dishes, these vibrant green peppers add flavor and nutrition. Enhance your meals with this versatile and healthy ingredient.",
    weight: "500g",
    dimensions: "15cm x 10cm x 8cm",
    color: "Brown",
    material: "Edible Product",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/pot-pan/o/d/z/ceramic-kd24-cs20-nirlon-original-imagwyykpfh9zfqg.jpeg?q=70",
    brand: "Nirlon",
    title: "NIRLON Ceramic 2-Piece Non Stick Induction Base Cookware",
    rating: 4,
    price: 1259,
    category: "Kitchen",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 10,
    description:
      "Nirlon Ceramic 2-Piece Non-Stick Induction Base Cookware: Upgrade your kitchen with Nirlon's premium ceramic cookware set. This 2-piece set features non-stick surfaces and induction base compatibility, perfect for hassle-free cooking. Enjoy easy cleaning and efficient cooking with this durable and stylish cookware.",
    weight: "2.5 kg",
    dimensions: "30cm x 20cm x 10cm",
    color: "Multicolor",
    material: "Ceramic",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/kajal/g/2/x/-original-imagkzhtcwtg3emj.jpeg?q=70",
    brand: "Lakmé",
    title: "Lakmé Ananyas Eyeconic Makeup Kit",
    rating: 4.5,
    price: 470,
    category: "Beauty & Cosmetic",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 11,
    description:
      "Lakmé Ananyas Eyeconic Makeup Kit: Elevate your makeup game with Lakmé's Ananyas Eyeconic Makeup Kit. This all-in-one kit includes essentials for stunning eye makeup looks, curated by Lakmé in collaboration with Ananya Panday. Achieve effortlessly glamorous eyes with this must-have kit.",
    weight: "300g",
    dimensions: "15cm x 10cm x 5cm",
    color: "Multicolor",
    material: "cream",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/moisturizer-cream/u/d/i/200-super-light-gel-non-sticky-fresh-feel-moisturiser-for-original-imahf3dwzx3k6apb.jpeg?q=70",
    brand: "Ponds",
    title: "PONDs Super Light Gel Non-Sticky Fresh Feel Moisturiser",
    rating: 4.5,
    price: 275,
    category: "Beauty & Cosmetic",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 12,
    description:
      "POND'S Super Light Gel Non-Sticky Fresh Feel Moisturizer: Experience hydration without the heavy feel with POND'S Super Light Gel Moisturizer. This non-sticky formula gives your skin a fresh, lightweight feel while providing deep hydration. Keep your skin moisturized and refreshed all day long.",
    weight: "50g",
    dimensions: "10cm x 5cm x 3cm",
    color: "White",
    material: "Plastic",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/brush-applicator/y/3/v/-original-imahygdcczahqgx5.jpeg?q=70",
    brand: "MINARA",
    title: "MINARA Makeup Brush Applicator Set of 15",
    rating: 4,
    price: 181,
    category: "Beauty & Cosmetic",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 13,
    description:
      "MINARA Makeup Brush Applicator Set of 15: Elevate your makeup routine with the MINARA Makeup Brush Applicator Set. This set includes 15 high-quality brushes for flawless application, blending, and precision. Achieve professional-level makeup looks with ease using this versatile brush set.",
    weight: "300g",
    dimensions: "20cm x 15cm x 5cm",
    color: "Mulicolor",
    material: "plastic",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/kq5iykw0/soap/n/s/d/pure-gentle-bathing-bar-pears-original-imag48gcxhfm3pmy.jpeg?q=70",
    brand: "Pears",
    title:
      "Pears Pure & Gentle Bar, Paraben-Free Body For Soft Skin  (8 x 125 g)",
    rating: 4,
    price: 580,
    category: "Beauty & Cosmetic",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 14,
    description:
      "Pears Pure & Gentle Bar, Paraben-Free Body For Soft Skin (8 x 125g): Experience the purity of Pears with this paraben-free, gentle body bar. Each bar, weighing 125g, is designed to cleanse and nourish, leaving your skin soft and refreshed. Enjoy a refreshing and gentle bathing experience.",
    weight: "Each bar, weighing 125g",
    dimensions: "7cm x 3cm x 2cm",
    color: "Brown",
    material: "Soap",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/drinks-juice/z/e/t/1-litchi-juice-goodness-of-fiber-tetrapack-2-b-natural-original-imagnffyzecehzkc.jpeg?q=70",
    brand: "B Natural",
    title:
      "B Natural Litchi Juice, Goodness of fiber, Vitamin C & E  (2 x 1 L)",
    rating: 4.5,
    price: 209,
    category: "Food products",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 15,
    description:
      "B Natural Litchi Juice, Goodness of Fiber, Vitamin C & E . Indulge in the refreshing taste of B Natural Litchi Juice, packed with the goodness of fiber, Vitamin C, and E. Each pack contains 1 liter, perfect for quenching your thirst and boosting your health. Dimensions per pack: . Enjoy a flavorful and nutritious beverage.",
    weight: "(2 x 1 L)",
    dimensions: "25cm x 10cm x 5cm",
    color: "White",
    material: "In Paper Bag",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/l3dcl8w0/aerated-drink/a/m/i/-original-imageg4mqpdtxues.jpeg?q=70",
    brand: "Thums Up",
    title: "Thums Up Soft Drink PET Bottle  (750 ml)",
    rating: 4.5,
    price: 36,
    category: "Food products",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 16,
    description:
      "Thums Up Soft Drink PET Bottle (750ml): Quench your thirst with the bold and intense flavor of Thums Up Soft Drink. This PET bottle contains 750ml of the iconic cola beverage, perfect for enjoying on the go or with meals. Experience the unique taste of Thums Up.",
    weight: "750ml",
    dimensions: "25cm x 8cm x 8cm",
    color: "Black",
    material: "Plactic Bottle",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/kqe3low0/milk/g/x/h/taaza-homogenised-toned-milk-tetrapack-toned-amul-original-imag4ethfyz9ymzt.jpeg?q=70",
    brand: "Amul",
    title: "Amul Taaza Homogenised Toned Milk  (1 L)",
    rating: 4,
    price: 70,
    category: "Food products",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 17,
    description:
      "Amul Taaza Homogenised Toned Milk (1L): Experience the goodness of Amul Taaza Homogenised Toned Milk. This 1-liter pack of milk is homogenized for a smooth texture and toned for reduced fat content, making it a healthy choice for your daily needs. Enjoy the rich taste and nutrition of Amul milk.",
    weight: "1-liter",
    dimensions: " 20cm x 10cm x 5cm",
    color: "White",
    material: "Plastic or Paper bag",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/312/312/k6v2ykw0/milk-powder/u/p/y/200-dairy-whitener-nestle-everyday-original-imafp8fpxg85utzt.jpeg?q=70",
    brand: "Nestle",
    title: "Nestle Everyday Dairy Whitener Milk Powder  (200 g)",
    rating: 4.5,
    price: 125,
    category: "Food products",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 18,
    description:
      "Nestle Everyday Dairy Whitener Milk Powder (200g): Enhance your beverages with Nestle Everyday Dairy Whitener Milk Powder. This 200g pack of milk powder is perfect for adding creaminess and richness to your tea, coffee, or other drinks. Enjoy a delightful and convenient way to elevate your drinks.",
    weight: "200g",
    dimensions: "15cm x 10cm x 3cm",
    color: "White",
    material: "Plastic Pouch",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/m/f/g34-5g-pb1v0002in-motorola-original-imagwu4rayqhgfjh.jpeg?q=70",
    brand: "Motorola",
    title: "Motorola G34 5G (Ocean Green, 128 GB)  (8 GB RAM)",
    rating: 4,
    price: 11999,
    category: "Electronics",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 19,
    description:
      "Motorola G34 5G (Ocean Green, 128GB) (8GB RAM): Dive into the future of connectivity with the Motorola G34 5G smartphone. Featuring 128GB storage and 8GB RAM, this Ocean Green device combines performance with style. Dimensions: . Experience seamless multitasking and blazing-fast 5G speeds with Motorola's advanced technology.",
    weight: "400g",
    dimensions: "16cm x 8cm x 1cm",
    color: "Starlight Blue",
    material: "Plastic + Glass",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/electrical-wire/k/2/u/-original-imagqy2y68gsc5v5.jpeg?q=70",
    brand: "Polycap",
    title: "Polycab Optima Plus 0.75 sq/mm Red 90 m Wire  (Red)",
    rating: 4.5,
    price: 949,
    category: "Electronics",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 20,
    description:
      "Polycab Optima Plus 0.75 sq/mm Red 90m Wire (Red): Ensure safety and efficiency with Polycab Optima Plus wires. This 0.75 sq/mm wire in red color comes in a 90m length, ideal for electrical installations and wiring projects. Dimensions: 10cm x 10cm x 10cm. Trust Polycab for reliable and durable electrical solutions.",
    weight: "3.25 Kg",
    dimensions: "Plus 0.75 sq/mm 90m",
    color: "Red",
    material: "Plastic cotted",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/rice-light/d/f/g/200-string-3-1-curtain-lights-artificial-vines-curtain-lights-original-imagtfwx3tngzkp3.jpeg?q=70",
    brand: "TechPride",
    title: "TechPride 200 LEDs 3 m Yellow Flickering String Rice Lights",
    rating: 4,
    price: 432,
    category: "Electronics",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 21,
    description:
      "TechPride 200 LEDs 3m Yellow Flickering String Rice Lights: Create a warm and cozy atmosphere with TechPride's 200 LEDs 3m Yellow Flickering String Rice Lights. Perfect for decorating indoors or outdoors, these lights add a festive touch to any space. Dimensions: 15cm x 10cm x 5cm. Illuminate your surroundings with style and elegance.",
    weight: "750g",
    dimensions: "15cm x 10cm x 5cm",
    color: "Multicolor or Yellow",
    material: "Plastic",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/n/i/6/30-01-jean-loose-black-nayak-fashion-original-imagvagjf9quxsbt.jpeg?q=70",
    brand: "Levis",
    title: "Men Jogger Fit Mid Rise Black Jeans",
    rating: 3.5,
    price: 1600,
    category: "Clothing",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 22,
    description:
      "Levi's Men Jogger Fit Mid Rise Black Jeans: Elevate your casual style with Levi's Men's Jogger Fit Mid Rise Black Jeans. Featuring a comfortable jogger fit and a stylish black color, these jeans are perfect for everyday wear. Dimensions: . Step out in style with Levi's iconic denim.",
    weight: "680g",
    dimensions: "30cm x 20cm x 5cm",
    color: "Black",
    material: "Denim + Cotton",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/kj8wccw0-0/jacket/w/p/s/m-12288810-roadster-original-imafyurnczcf6rrq.jpeg?q=70",
    brand: "Roadster",
    title: "Men Washed Jacket",
    rating: 4,
    price: 1150,
    category: "Clothing",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 23,
    description:
      "Roadster Men Washed Jacket: Embrace rugged style with Roadster's Men Washed Jacket. This jacket features a vintage washed look, perfect for adding a touch of casual cool to your outfit.. Stay effortlessly stylish and comfortable with Roadster's versatile jacket.",
    weight: "1.25Kg",
    dimensions: "35cm x 25cm x 10cm",
    color: "Dark Blue",
    material: "Cotton + Polyaster + Cotton",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/o/0/c/m-wm17-ss01-grey-alan-jones-original-imaghhyjzz553epq.jpeg?q=70",
    brand: "Alan Jones",
    title: "Women Full Sleeve Solid Hooded Sweatshirt",
    rating: 4.5,
    price: 899,
    category: "Clothing",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 24,
    description:
      " Alan Jones Women Full Sleeve Solid Hooded Sweatshirt: Stay cozy and stylish with Alan Jones Women's Full Sleeve Solid Hooded Sweatshirt. This sweatshirt is perfect for chilly days, featuring a hood and full sleeves for added warmth. . Elevate your casual look with this comfortable and fashionable sweatshirt from Alan Jones.",
    weight: "1.2Kg",
    dimensions: "30cm x 20cm x 5cm",
    color: "White",
    material: "Woollen",
  },
  {
    imgSrc:
      "https://rukminim2.flixcart.com/image/612/612/xif0q/art-set/l/k/e/-original-imagqzfwc8dzpmj3.jpeg?q=70",
    brand: "DOMS",
    title: "DOMS Junior Art Kit",
    rating: 4.5,
    price: 425,
    category: "Stationery",
    brandLink: "/brand/brand2",
    productLink: "/products/details/:id",
    id: 25,
    description:
      "DOMS Junior Art Kit: Unleash creativity with the DOMS Junior Art Kit. This comprehensive kit includes a variety of art supplies, perfect for young artists to explore and express their imagination. . Inspire artistic endeavors and hours of creative fun with DOMS.",
    weight: "580g",
    dimensions: "25cm x 20cm x 10cm",
    color: "Multicolor",
    material: "Plastic",
  },
];

export default products;
